name: pr
on: 
  pull_request:
    paths-ignore:
    - infrastructure/README.md

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    secrets: inherit

  tfdocs:
    uses: ./.github/workflows/tfdocs.yml
    needs: [validate]
    secrets: inherit